# Generated by Django 5.0.3 on 2024-03-15 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PupilsModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('spec', models.CharField(max_length=100, verbose_name='Speciality')),
                ('res_1', models.IntegerField(verbose_name='Birinchi oy natijasi')),
                ('res_2', models.IntegerField(verbose_name='Ikkinchi oy natijasi')),
                ('res_3', models.IntegerField(verbose_name='Uchinchi oy natijasi')),
                ('res_4', models.IntegerField(verbose_name="To'rtinchi oy natijasi")),
                ('res_5', models.IntegerField(verbose_name='Beshinchi oy natijasi')),
            ],
        ),
    ]
