# Generated by Django 5.0.3 on 2024-03-15 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pupils', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pupilsmodels',
            name='pupil_img',
            field=models.ImageField(default=1, upload_to='', verbose_name='Pupil Image'),
            preserve_default=False,
        ),
    ]
